### Step 1: Install Required Libraries

In [ ]:
pip install selenium webdriver-manager pandas beautifulsoup4

### Step 2: Import Libraries

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import re  # For cleaning text using regex
from bs4 import BeautifulSoup

import warnings

# Suppress warnings
warnings.filterwarnings("ignore")

### Step 3: Set Up Selenium WebDriver

In [3]:
# Set up Selenium WebDriver
chrome_options = Options()
chrome_options.add_argument("--headless")  # Run in headless mode
chrome_options.add_argument("--disable-gpu")  # Disable GPU acceleration
chrome_options.add_argument("--window-size=1920,1080")  # Set window size

# Initialize the WebDriver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

### Step 4: Load the Web Page
Load the target URL and wait for the initial cards to load.

In [5]:
# URL of the page to scrape
url = "https://www.coursera.org/career-academy?trk_ref=globalnav"

# Load the page
driver.get(url)

# Wait for the initial cards to load
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CLASS_NAME, "cds-9.css-b1mnpw.cds-11.cds-grid-item"))
    )
except Exception as e:
    print(f"Error waiting for initial cards to load: {e}")
    driver.quit()
    exit()

### Step 5: Click the "View All" Button
Locate and click the "View all (31 more)" button to load additional cards.

In [7]:
# Click the "View all (31 more)" button to load additional cards
try:
    view_all_button = driver.find_element(By.CSS_SELECTOR, 'button[data-track-component="view_all_career_cards"]')
    view_all_button.click()
    
    # Wait for the additional cards to load
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CLASS_NAME, "cds-9.css-b1mnpw.cds-11.cds-grid-item"))
    )
except Exception as e:
    print(f"Error clicking the 'View all' button or waiting for additional cards: {e}")
    driver.quit()
    exit()

### Step 6: Parse the Page with BeautifulSoup
Use BeautifulSoup to parse the page source and extract all cards.

In [9]:
# Get the page source and parse it with BeautifulSoup
soup = BeautifulSoup(driver.page_source, 'html.parser')

# Find all the cards with the specified class
cards = soup.find_all('div', class_='cds-9 css-b1mnpw cds-11 cds-grid-item')

print(f"Number of cards found: {len(cards)}")

Number of cards found: 43

### Step 7: Extract Data from Each Card
Loop through each card and extract the title, description, median salary, and jobs available. Use regex to clean the salary and jobs available text.

In [12]:
# Initialize a list to store the data
data = []

# Loop through each card and extract the details
for card in cards:
    try:
        # Extract the title
        title_element = card.find('h2', class_='cds-119 cds-Typography-base css-bbd009 cds-121')
        
        if title_element:
            title = title_element.text.strip()
        else:
            title = "Title not found"
            print("Title not found in card:", card.prettify())  # Debugging: Print the card HTML
        
        # Extract the description
        description = card.find('p', class_='css-4s48ix').text.strip()
        
        # Extract the salary and jobs available
        salary_jobs = card.find('div', class_='css-hr97go').text.strip()
        
        # Use regex to extract only the numbers
        median_salary = re.search(r'\$\d{1,3}(?:,\d{3})*', salary_jobs).group()  # Extract $90,500
        jobs_available = re.search(r'\d{1,3}(?:,\d{3})*', salary_jobs.split('jobs')[0]).group()  # Extract 82,489
        
        # Append the extracted data to the list
        data.append({
            'Title': title,
            'Description': description,
            'Median Salary': median_salary,
            'Jobs Available': jobs_available
        })
    except AttributeError as e:
        print(f"Error extracting data from a card: {e}")
        continue

### Step 8: Convert Data to a DataFrame
Convert the list of dictionaries into a pandas DataFrame.

In [14]:
# Convert the list to a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame as a table
print(df)

                               Title  \
0                       Data Analyst
1                    Project Manager
2         Cybersecurity Professional
3                        UX Designer
4              IT Support Specialist
5                   Digital Marketer
6                     Data Scientist
7               Supply Chain Analyst
8                    Product Manager
9               Full Stack Developer
10                        Bookkeeper
11               Front-End Developer
12             Social Media Marketer
13     Business Intelligence Analyst
14             Application Developer
15        Human Resources Specialist
16                     Data Engineer
17                Back-End Developer
18                   DevOps Engineer
19             Technology Consultant
20       Sales Operations Specialist
21                     iOS Developer
22                 Marketing Analyst
23                IT Project Manager
24                 Android Developer
25  Sales Development Representative
26                      Career Coach
27          Data Warehouse Developer
28                  Network Engineer
29   Customer Service Representative
30                        Accountant
31               Solutions Architect
32                 Real Estate Agent
33           Cloud Support Associate
34              Compensation Analyst
35                Payroll Specialist
36                  Personal Trainer
37             Insurance Sales Agent
38                     Game Designer
39              Mobile App Developer
40       Public Relations Specialist
41                   Program Manager
42                  Business Analyst

                                          Description Median Salary  \
0   Collect, organize, and transform data to make ...       $90,500
1   Oversee the planning and execution of projects...      $102,800
2   Develop strategies to protect organizations fr...      $119,700
3   Make digital and physical products easier and ...      $121,200
4   Evaluate and troubleshoot technology issues so...       $56,200
5   Define and develop digital strategies to deliv...       $61,300
6   Extract and analyze data to make informed busi...      $138,100
7   Streamline supply chain operations and drive e...       $65,900
8   Oversee the entirety of a product's lifecycle,...      $140,200
9   Create both front-end and back-end components ...      $129,900
10  Record financial transactions and manage finan...       $45,700
11  Design and develop the look, feel, function, a...      $130,900
12  Social media specialists establish, build, and...       $50,000
13  Make data-driven decisions through SQL-based d...      $110,000
14  Analyze customer needs and design systems and ...      $114,600
15  Recruit and place individuals within an organi...       $52,100
16  Design and build systems to collect and transf...      $130,000
17  Build the structures that help websites functi...      $148,400
18  Build the tools & infrastructure to allow comp...      $135,000
19  Provide clients with strategic guidance on the...      $104,300
20  Create strategies that support sales teams to ...       $49,000
21  Build and write code for mobile apps hosted on...      $140,200
22  Perform research and gather data to help compa...       $87,400
23  Oversee IT projects, ensuring they are complet...      $120,200
24  Build and write code for mobile apps hosted on...      $141,200
25  Work with prospective customers to help them i...       $64,900
26  Help individuals plan their career choices thr...       $48,000
27  Design and build systems to collect, transform...       $76,200
28  Monitor, troubleshoot, and maintain networks i...       $80,300
29  Troubleshoot, communicate, and maintain record...       $37,600
30  Support senior accountants by managing, prepar...       $67,500
31  Work closely with clients to implement and sup...      $122,800
32  Facilitate property transactions by listing pr...       $75,200
33  Manage and support end-user cloud technologies...      $141,200
34  If you like strategic thinking, collaboration,...       $56,700
35  If you like data management, organizational sk...       $54,100
36  Help clients achieve their health and fitness ...       $52,200
37  Connect clients with tailored insurance soluti...       $57,500
38  Create engaging gaming experiences by designin...      $121,200
39  Build, test, and update user-friendly apps, co...      $124,800
40  Manage an organization's public image through ...       $60,000
41  Manage multiple projects to meet strategic goa...       $70,000
42  Bridge business needs and technical solutions ...       $94,600

   Jobs Available
0          90,500
1         102,800
2         119,700
3         121,200
4          56,200
5          61,300
6         138,100
7          65,900
8         140,200
9         129,900
10         45,700
11        130,900
12         50,000
13        110,000
14        114,600
15         52,100
16        130,000
17        148,400
18        135,000
19        104,300
20         49,000
21        140,200
22         87,400
23        120,200
24        141,200
25         64,900
26         48,000
27         76,200
28         80,300
29         37,600
30         67,500
31        122,800
32         75,200
33        141,200
34         56,700
35         54,100
36         52,200
37         57,500
38        121,200
39        124,800
40         60,000
41         70,000
42         94,600

### Step 9: Save the DataFrame as a CSV File
Save the DataFrame to a CSV file for further analysis or sharing.

In [16]:
# Save the DataFrame to a CSV file
df.to_csv('career_academy_data.csv', index=False)

print("Data saved to 'career_academy_data.csv'")

Data saved to 'career_academy_data.csv'

### Step 10: Close the Browser
Close the Selenium WebDriver to free up resources.

In [19]:
# Close the browser
driver.quit()

In [20]:
df

,Title,Description,Median Salary,Jobs Available
0,Data Analyst,"Collect, organize, and transform data to make ...","$90,500","90,500"
1,Project Manager,Oversee the planning and execution of projects...,"$102,800","102,800"
2,Cybersecurity Professional,Develop strategies to protect organizations fr...,"$119,700","119,700"
3,UX Designer,Make digital and physical products easier and ...,"$121,200","121,200"
4,IT Support Specialist,Evaluate and troubleshoot technology issues so...,"$56,200","56,200"
5,Digital Marketer,Define and develop digital strategies to deliv...,"$61,300","61,300"
6,Data Scientist,Extract and analyze data to make informed busi...,"$138,100","138,100"
7,Supply Chain Analyst,Streamline supply chain operations and drive e...,"$65,900","65,900"
8,Product Manager,"Oversee the entirety of a product's lifecycle,...","$140,200","140,200"
9,Full Stack Developer,Create both front-end and back-end components ...,"$129,900","129,900"
10,Bookkeeper,Record financial transactions and manage finan...,"$45,700","45,700"
11,Front-End Developer,"Design and develop the look, feel, function, a...","$130,900","130,900"
12,Social Media Marketer,"Social media specialists establish, build, and...","$50,000","50,000"
13,Business Intelligence Analyst,Make data-driven decisions through SQL-based d...,"$110,000","110,000"
14,Application Developer,Analyze customer needs and design systems and ...,"$114,600","114,600"
15,Human Resources Specialist,Recruit and place individuals within an organi...,"$52,100","52,100"
16,Data Engineer,Design and build systems to collect and transf...,"$130,000","130,000"
17,Back-End Developer,Build the structures that help websites functi...,"$148,400","148,400"
18,DevOps Engineer,Build the tools & infrastructure to allow comp...,"$135,000","135,000"
19,Technology Consultant,Provide clients with strategic guidance on the...,"$104,300","104,300"
20,Sales Operations Specialist,Create strategies that support sales teams to ...,"$49,000","49,000"
21,iOS Developer,Build and write code for mobile apps hosted on...,"$140,200","140,200"
22,Marketing Analyst,Perform research and gather data to help compa...,"$87,400","87,400"
23,IT Project Manager,"Oversee IT projects, ensuring they are complet...","$120,200","120,200"
24,Android Developer,Build and write code for mobile apps hosted on...,"$141,200","141,200"
25,Sales Development Representative,Work with prospective customers to help them i...,"$64,900","64,900"
26,Career Coach,Help individuals plan their career choices thr...,"$48,000","48,000"
27,Data Warehouse Developer,"Design and build systems to collect, transform...","$76,200","76,200"
28,Network Engineer,"Monitor, troubleshoot, and maintain networks i...","$80,300","80,300"
29,Customer Service Representative,"Troubleshoot, communicate, and maintain record...","$37,600","37,600"
30,Accountant,"Support senior accountants by managing, prepar...","$67,500","67,500"
31,Solutions Architect,Work closely with clients to implement and sup...,"$122,800","122,800"
32,Real Estate Agent,Facilitate property transactions by listing pr...,"$75,200","75,200"
33,Cloud Support Associate,Manage and support end-user cloud technologies...,"$141,200","141,200"
34,Compensation Analyst,"If you like strategic thinking, collaboration,...","$56,700","56,700"
35,Payroll Specialist,"If you like data management, organizational sk...","$54,100","54,100"
36,Personal Trainer,Help clients achieve their health and fitness ...,"$52,200","52,200"
37,Insurance Sales Agent,Connect clients with tailored insurance soluti...,"$57,500","57,500"
38,Game Designer,Create engaging gaming experiences by designin...,"$121,200","121,200"
39,Mobile App Developer,"Build, test, and update user-friendly apps, co...","$124,800","124,800"
40,Public Relations Specialist,Manage an organization's public image through ...,"$60,000","60,000"
41,Program Manager,Manage multiple projects to meet strategic goa...,"$70,000","70,000"
42,Business Analyst,Bridge business needs and technical solutions ...,"$94,600","94,600"

In [29]:
# Convert 'Median Salary' to numeric for sorting
df['Salary'] = df['Median Salary'].replace('[\$,]', '', regex=True).astype(float)

# Sort by 'Median Salary' in descending order
df_sorted = df.sort_values(by='Salary', ascending=False)

# Convert 'Median Salary' back to formatted string
df_sorted['Salary'] = df_sorted['Salary'].apply(lambda x: f"${x:,.0f}")

# Display the sorted DataFrame
print(df_sorted[['Title', 'Salary']])

                               Title    Salary
17                Back-End Developer  $148,400
33           Cloud Support Associate  $141,200
24                 Android Developer  $141,200
21                     iOS Developer  $140,200
8                    Product Manager  $140,200
6                     Data Scientist  $138,100
18                   DevOps Engineer  $135,000
11               Front-End Developer  $130,900
16                     Data Engineer  $130,000
9               Full Stack Developer  $129,900
39              Mobile App Developer  $124,800
31               Solutions Architect  $122,800
38                     Game Designer  $121,200
3                        UX Designer  $121,200
23                IT Project Manager  $120,200
2         Cybersecurity Professional  $119,700
14             Application Developer  $114,600
13     Business Intelligence Analyst  $110,000
19             Technology Consultant  $104,300
1                    Project Manager  $102,800
42                  Business Analyst   $94,600
0                       Data Analyst   $90,500
22                 Marketing Analyst   $87,400
28                  Network Engineer   $80,300
27          Data Warehouse Developer   $76,200
32                 Real Estate Agent   $75,200
41                   Program Manager   $70,000
30                        Accountant   $67,500
7               Supply Chain Analyst   $65,900
25  Sales Development Representative   $64,900
5                   Digital Marketer   $61,300
40       Public Relations Specialist   $60,000
37             Insurance Sales Agent   $57,500
34              Compensation Analyst   $56,700
4              IT Support Specialist   $56,200
35                Payroll Specialist   $54,100
36                  Personal Trainer   $52,200
15        Human Resources Specialist   $52,100
12             Social Media Marketer   $50,000
20       Sales Operations Specialist   $49,000
26                      Career Coach   $48,000
10                        Bookkeeper   $45,700
29   Customer Service Representative   $37,600

In [31]:
df

,Title,Description,Median Salary,Jobs Available,Salary
0,Data Analyst,"Collect, organize, and transform data to make ...","$90,500","90,500",90500.0
1,Project Manager,Oversee the planning and execution of projects...,"$102,800","102,800",102800.0
2,Cybersecurity Professional,Develop strategies to protect organizations fr...,"$119,700","119,700",119700.0
3,UX Designer,Make digital and physical products easier and ...,"$121,200","121,200",121200.0
4,IT Support Specialist,Evaluate and troubleshoot technology issues so...,"$56,200","56,200",56200.0
5,Digital Marketer,Define and develop digital strategies to deliv...,"$61,300","61,300",61300.0
6,Data Scientist,Extract and analyze data to make informed busi...,"$138,100","138,100",138100.0
7,Supply Chain Analyst,Streamline supply chain operations and drive e...,"$65,900","65,900",65900.0
8,Product Manager,"Oversee the entirety of a product's lifecycle,...","$140,200","140,200",140200.0
9,Full Stack Developer,Create both front-end and back-end components ...,"$129,900","129,900",129900.0
10,Bookkeeper,Record financial transactions and manage finan...,"$45,700","45,700",45700.0
11,Front-End Developer,"Design and develop the look, feel, function, a...","$130,900","130,900",130900.0
12,Social Media Marketer,"Social media specialists establish, build, and...","$50,000","50,000",50000.0
13,Business Intelligence Analyst,Make data-driven decisions through SQL-based d...,"$110,000","110,000",110000.0
14,Application Developer,Analyze customer needs and design systems and ...,"$114,600","114,600",114600.0
15,Human Resources Specialist,Recruit and place individuals within an organi...,"$52,100","52,100",52100.0
16,Data Engineer,Design and build systems to collect and transf...,"$130,000","130,000",130000.0
17,Back-End Developer,Build the structures that help websites functi...,"$148,400","148,400",148400.0
18,DevOps Engineer,Build the tools & infrastructure to allow comp...,"$135,000","135,000",135000.0
19,Technology Consultant,Provide clients with strategic guidance on the...,"$104,300","104,300",104300.0
20,Sales Operations Specialist,Create strategies that support sales teams to ...,"$49,000","49,000",49000.0
21,iOS Developer,Build and write code for mobile apps hosted on...,"$140,200","140,200",140200.0
22,Marketing Analyst,Perform research and gather data to help compa...,"$87,400","87,400",87400.0
23,IT Project Manager,"Oversee IT projects, ensuring they are complet...","$120,200","120,200",120200.0
24,Android Developer,Build and write code for mobile apps hosted on...,"$141,200","141,200",141200.0
25,Sales Development Representative,Work with prospective customers to help them i...,"$64,900","64,900",64900.0
26,Career Coach,Help individuals plan their career choices thr...,"$48,000","48,000",48000.0
27,Data Warehouse Developer,"Design and build systems to collect, transform...","$76,200","76,200",76200.0
28,Network Engineer,"Monitor, troubleshoot, and maintain networks i...","$80,300","80,300",80300.0
29,Customer Service Representative,"Troubleshoot, communicate, and maintain record...","$37,600","37,600",37600.0
30,Accountant,"Support senior accountants by managing, prepar...","$67,500","67,500",67500.0
31,Solutions Architect,Work closely with clients to implement and sup...,"$122,800","122,800",122800.0
32,Real Estate Agent,Facilitate property transactions by listing pr...,"$75,200","75,200",75200.0
33,Cloud Support Associate,Manage and support end-user cloud technologies...,"$141,200","141,200",141200.0
34,Compensation Analyst,"If you like strategic thinking, collaboration,...","$56,700","56,700",56700.0
35,Payroll Specialist,"If you like data management, organizational sk...","$54,100","54,100",54100.0
36,Personal Trainer,Help clients achieve their health and fitness ...,"$52,200","52,200",52200.0
37,Insurance Sales Agent,Connect clients with tailored insurance soluti...,"$57,500","57,500",57500.0
38,Game Designer,Create engaging gaming experiences by designin...,"$121,200","121,200",121200.0
39,Mobile App Developer,"Build, test, and update user-friendly apps, co...","$124,800","124,800",124800.0
40,Public Relations Specialist,Manage an organization's public image through ...,"$60,000","60,000",60000.0
41,Program Manager,Manage multiple projects to meet strategic goa...,"$70,000","70,000",70000.0
42,Business Analyst,Bridge business needs and technical solutions ...,"$94,600","94,600",94600.0